### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by tmbdev** [libdynd/libdynd#739]
I tried building and installing on Ubuntu 15.04 and it's failing when compiling libdynd_benchmarks.cpp with #include <benchmarks/benchmark.h> not found.

**Comment by izaid** [comment]
Which #include is the problem? Google benchmark is quite good, but we've had a couple of issues with it.

You can also just disable the benchmarks by passing -DDYND_BUILD_BENCHMARKS=OFF to cmake ..

**Comment by insertinterestingnamehere** [comment]
This looks like what happens when a submodule doesn't get cloned with the git repo. For some reason git doesn't clone submodules automatically when you initially clone the repository. Running `git submodule update --init --recursive` should fix it. See also http://stackoverflow.com/a/4438292/1935144.

**Comment by tmbdev** [comment]
Thanks; that fixed it. It might be worth pointing out in the build instructions. You might also configure DYND_BUILD_BENCHMARKS=OFF automatically when the benchmarks haven't been checked out.

**Comment by izaid** [comment]
You are absolutely right, @tmbdev, those are things we should (and will) do. :)
