### ISSUE TITLE
Git Version is wrong

### ISSUE THREAD

**Issue by insertinterestingnamehere** [libdynd/libdynd#992]
Our currently listed git version is wrong in both libdynd and dynd-python. libdynd seems to think it's still a dev version of dynd 6.3 and dynd-python thinks it's a dev version of dynd 6.6. Both should say something like 0.7.2-(git SHA here).

**Comment by mwiebe** [comment]
This was because the tags were created with just `git tag v0.7.1` instead of `git tag -a v0.7.1`. This is one of the weird git snafu UI design choices where the default choice is not the "generally recommended" option, see https://git-scm.com/book/en/v2/Git-Basics-Tagging#Creating-Tags

I've force-pushed an annotated tag of v0.7.1 to both libdynd and dynd-python

**Comment by mwiebe** [comment]
Note also that you may have to do a `git fetch` to get all the tags locally, and get the proper version listed via the `git describe` command.

**Comment by insertinterestingnamehere** [comment]
Wow. That's odd git behavior. Thanks for clearing this up.
